spring.application.name=targy-review

spring.datasource.url=jdbc:postgresql://localhost:5432/kir_dev_subject_reviewer
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true